### ISSUE TITLE
Add Styled Components

### ISSUE THREAD

**Issue by jamesvclements** [dpopp07/bartop#22]
I've never used [Styled Components](https://www.styled-components.com/) before, but I think this would be a cool opportunity to try out CSS in JS. It works out of the box w/ CRA, and there are also some [examples](https://github.com/withspectrum/react-app-rewire-styled-components) of ways to add the babel plugins / lint integrations without ejecting from CRA.

Alternatively, we could stick w/ one of the classic component libraries like [Bootstrap](http://getbootstrap.com/) or [Semantic UI](https://semantic-ui.com/). These would probably speed along development more.

**Comment by dpopp07** [comment]
Styled components seems pretty cool. I would agree that this is a good opportunity to try something new. I don't know much about any of these libraries and don't know how much I'll use them so go with anything you'd like - I'll support you no matter what 👪

**Comment by dpopp07** [comment]
Moving this to icebox until you decide if you want to use them or not.

**Comment by jamesvclements** [comment]
Okay I'm pulling the trigger on this - gonna add Styled Components and make a new issue for also adding [Rebass](http://jxnblk.com/rebass/)
