### ISSUE TITLE
Configure Codecov for target coverage

### ISSUE THREAD

**Issue by dpopp07** [dpopp07/bartop#38]
You can set up a [config file](https://docs.codecov.io/docs/commit-status) that allows you to require a certain target coverage to pass CI. I'll set this up with a really low target until we get the client tests up and running, then increase it.

Also, inbox daddy doesn't want any more emails from Codecov so I'll be setting up slack notifications too

**Comment by jamesvclements** [comment]
I mentioned this in #37 as well for updating the client tests so we can set a limit, but whichever happens first doesn't matter ;)
