### ISSUE TITLE
Decide on linting preferences

### ISSUE THREAD

**Issue by dpopp07** [dpopp07/bartop#4]
We should decide what we want our coding style to be and add a .eslintrc (or something like that) to the repo.

**Comment by dpopp07** [comment]
We can add these to a wiki or our notes once decided if we want to keep them somewhere.

**Comment by jamesvclements** [comment]
I think there are two approaches:
* we have separate (but potentially equal) linting rules for the client and server, keeping them as if they're independent
* we have one linter setup for the whole repo

> Create React App intentionally provides a minimal set of rules that find common mistakes.

So there are some ESLint rules running behind the scenes in the client already. Check out [Prettier](https://github.com/prettier/prettier). We could use ESLint for the code quality rules and Prettier for the style rules. I think having one set of rules (eslint & prettier) for the whole repo would be nice. Not sure if having the client ES6 and server ES5 would complicate that though 🤔

**Comment by dpopp07** [comment]
Prettier has pissed me off in some repos I've worked in lol but yes I agree we should use it and ESLint together. 

So I wouldn't mind separating the linting rules to keep our microstructure thing goin and because that way we could each write code the way we want to haha. But I also think it would be nice to maintain a consistent style throughout the project.

I read a few articles and I feel pretty convinced to write the most modern-style JS possible and then transpile. So it shouldn't be too complicated to follow the same rules. Maybe we start with one set of rules for the whole project. If it becomes too complicated to maintain, we can always separate without too much trouble.

**Comment by jamesvclements** [comment]
Okay cool - so plan of action is to keep all the rules separate to maintain the microservice idea, but have the same or very similar rules to keep consistency?

**Comment by dpopp07** [comment]
I'm good with doing that. We still should talk about what those rules are. If they end up being the exact same, we should probably just use one set of rules for the whole repo.
