### ISSUE TITLE
Write a Swagger file for the API

### ISSUE THREAD

**Issue by dpopp07** [dpopp07/bartop#49]
This will be an ongoing issue but idk if it's modular enough to be an epic. I am going to write an [OpenAPI Document](https://swagger.io/specification/#oasDocument) to describe the API. This should help to write a more robust API and will make generating documentation very easy.

**Comment by dpopp07** [comment]
Now thinking that it will be easier to maintain this document as I write the API, rather than making them two separate entities. I'm going to make a file that exactly describes the current state of the REST API, push that, close this issue, and then update the Swagger with every update to the API in the same PRs.

**Comment by jamesvclements** [comment]
^ good looks
