### ISSUE TITLE
Add simple static page as domain placeholder

### ISSUE THREAD

**Issue by jamesvclements** [dpopp07/bartop#50]
Add a simple lightweight page at [bartop.io](bartop.io) that has a link to our GitHub repo as a little placeholder for the timebeing.

**Comment by jamesvclements** [comment]
I think [GitHub Pages](https://pages.github.com/) would be perfect for this

**Comment by dpopp07** [comment]
I was just thinking that GitHub Pages would be great here. Should be pretty easy to set up too

**Comment by dpopp07** [comment]
Not sure if this will be necessary or not, but Travis can [auto-deploy](https://docs.travis-ci.com/user/deployment/pages/) to GitHub pages. This is something we will certainly do for the production app on whatever cloud service we're on

**Comment by dpopp07** [comment]
@smvayda Please point our domain name to this url
