### ISSUE TITLE
Sketch out database architecture for users

### ISSUE THREAD

**Issue by dpopp07** [dpopp07/bartop#7]
Write out the database architecture so we know how to set up API calls to the DB.

**Comment by dpopp07** [comment]
I've written some stuff out on paper. Let's talk it over in person and adjust as we need to. I'd like to get this nailed down so I can start working on API endpoints

**Comment by dpopp07** [comment]
@jamesvclements based on what we talked about today, can we close this issue?

The referencing / linking of drinks can still be figured out later but if you're happy with the template layout for users we can close this.

**Comment by jamesvclements** [comment]
@dpopp07 Yeah I think this is good to go. As long as we're ready to make changes as we go along, I think that initial structure we talked about is a great starting point
